version: "3.8"
services:
  postgres:
    image: postgres:15
    container_name: techManager_postgres
    environment:
      POSTGRES_DB: techManager
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: senha1234
    ports:
      - "5432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d
    restart: unless-stopped

  adminer:
    image: adminer:latest
    container_name: techManager_adminer
    depends_on: [postgres]
    environment:
      ADMINER_DEFAULT_SERVER: postgres
    ports:
      - "9080:8080"
    restart: unless-stopped

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    container_name: techManager_backend
    environment:
      SPRING_PROFILES_ACTIVE: docker

    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped
